package bot.multifunction.model.enums.steps;

public enum Steps {
  CREATING_ONCE_REMINDER,
  CREATING_EVERYDAY_REMINDER,
  CREATING_EVEN_DAYS_REMINDER,
  CREATING_ODD_DAYS_REMINDER,
  SET_LOCATION,
  CHANGE_LOCATION;
}
